
lab50:
  windows:
    - editor
    - readme
    - terminal
  files:
    - !exclude "*"
    - !include water.py
    - !include puntjes.py
    - !include fahrenheit.py
    - !include wisselgeld.py
    - !include som.py
